version: "3"

services:
  backend-dev:
    restart: always
    image: person456/team6-backend
    container_name: backend-dev
    hostname: backend-dev
    # expose:
      # - "8080"
    ports:
      - "8080:8080"
    networks:
      - team6-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/team6db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: rootpassword
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    volumes:
      - /var/www/react-app:/usr/share/nginx/html
      - /var/www/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - team6-network
    ports:
      - "80:80"

networks:
  team6-network:
    driver: bridge
