version: "3"
networks:
  shared-network:
    driver: bridge


services:
  backend-dev:
    restart: always
    depends_on:
      - redis
    image: person456/team6-backend
    container_name: backend-dev
    hostname: backend-dev
    # expose:
    # - "8080"
    ports:
      - "8080:8080"
    networks:
      - shared-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-qakba-fkr.cdb.fin-ntruss.com:3306/team6
      SPRING_DATASOURCE_USERNAME: team6
      SPRING_DATASOURCE_PASSWORD: team6team6!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    volumes:
      - /var/www/react-app:/usr/share/nginx/html
      - /var/www/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared-network
    ports:
      - "80:80"
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: team6db
      MYSQL_USER: team6user
      MYSQL_PASSWORD: team6password
      TZ: Asia/Seoul
    volumes:
      - /var/www/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - shared-network

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - shared-network
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /var/www/redis/data:/data

volumes:
  mysql-data:
  redis-data:
